<?php
require_once 'config.php';
$pageTitle = 'QuickMed - Your Trusted Online Pharmacy | আপনার বিশ্বস্ত অনলাইন ফার্মেসি';
$pageDescription = 'Buy genuine medicines online with home delivery across Bangladesh. Best prices, fast delivery, 100% authentic products.';
include 'includes/header.php';
?>
<?php include 'includes/homepage/hero.php'; ?>
<?php include 'includes/homepage/stats.php'; ?>
<div class="mt-6 sm:mt-8"><?php include 'includes/homepage/categories.php'; ?></div>
<section class="py-8 sm:py-12 md:py-14 bg-gray-50 relative overflow-hidden">
    <div class="absolute top-0 left-0 w-full h-full opacity-[0.03] pointer-events-none"><div class="absolute top-6 left-6 text-6xl sm:text-8xl transform -rotate-12">📄</div><div class="absolute bottom-6 right-6 text-6xl sm:text-8xl transform rotate-12">📱</div></div>
    <div class="container mx-auto px-3 sm:px-4 relative z-10">
        <?php qm_section_head('Order via Prescription?', 'Three simple steps from prescription to doorstep.', 'Easy Process'); ?>
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4 md:gap-5 text-center max-w-5xl mx-auto">
            <div class="bg-white p-4 sm:p-5 rounded-xl shadow-sm border-b-[3px] border-lime-accent relative hover:-translate-y-1 hover:shadow-md transition-all duration-300" data-aos="fade-right"><div class="absolute -top-3 left-1/2 -translate-x-1/2 w-8 h-8 bg-deep-green text-white flex items-center justify-center rounded-full font-bold text-sm border-2 border-white shadow">1</div><div class="text-3xl sm:text-4xl mb-2.5 mt-2">📸</div><h3 class="text-[0.95rem] sm:text-[1.05rem] font-bold text-gray-800 mb-1.5">Upload Photo</h3><p class="text-gray-500 text-[0.78rem] sm:text-xs leading-relaxed">Clear photo of prescription and upload to system.</p></div>
            <div class="bg-white p-4 sm:p-5 rounded-xl shadow-sm border-b-[3px] border-lime-accent relative hover:-translate-y-1 hover:shadow-md transition-all duration-300" data-aos="fade-up" data-aos-delay="80"><div class="absolute -top-3 left-1/2 -translate-x-1/2 w-8 h-8 bg-deep-green text-white flex items-center justify-center rounded-full font-bold text-sm border-2 border-white shadow">2</div><div class="text-3xl sm:text-4xl mb-2.5 mt-2">👨‍⚕️</div><h3 class="text-[0.95rem] sm:text-[1.05rem] font-bold text-gray-800 mb-1.5">Doctor Review</h3><p class="text-gray-500 text-[0.78rem] sm:text-xs leading-relaxed">Certified pharmacists verify your medicine list.</p></div>
            <div class="bg-white p-4 sm:p-5 rounded-xl shadow-sm border-b-[3px] border-lime-accent relative hover:-translate-y-1 hover:shadow-md transition-all duration-300" data-aos="fade-left"><div class="absolute -top-3 left-1/2 -translate-x-1/2 w-8 h-8 bg-deep-green text-white flex items-center justify-center rounded-full font-bold text-sm border-2 border-white shadow">3</div><div class="text-3xl sm:text-4xl mb-2.5 mt-2">🚚</div><h3 class="text-[0.95rem] sm:text-[1.05rem] font-bold text-gray-800 mb-1.5">Fast Delivery</h3><p class="text-gray-500 text-[0.78rem] sm:text-xs leading-relaxed">Get medicines delivered within hours.</p></div>
        </div>
        <div class="text-center mt-6 sm:mt-8" data-aos="zoom-in"><a href="prescription-upload.php" class="btn btn-primary btn-lg text-[0.82rem] sm:text-[0.9rem] px-5 py-2.5"><span>📤</span> Upload Prescription Now</a></div>
    </div>
</section>
<?php include 'includes/homepage/flash_sale.php'; ?>
<?php include 'includes/homepage/featured.php'; ?>
<section class="py-10 sm:py-14 md:py-16 bg-deep-green text-white relative overflow-hidden">
    <div class="absolute inset-0 opacity-[0.06] pointer-events-none"><svg class="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M0 100 C 20 0 50 0 100 100 Z" fill="white" /></svg></div>
    <div class="container mx-auto px-3 sm:px-4 grid md:grid-cols-2 gap-6 sm:gap-8 md:gap-10 items-center relative z-10">
        <div data-aos="fade-right"><span class="inline-block text-lime-accent font-bold tracking-widest uppercase text-[10px] sm:text-xs border-b border-lime-accent pb-0.5 mb-3">Who We Are</span><h2 class="text-[1.4rem] sm:text-2xl md:text-3xl font-bold font-mono mb-3 sm:mb-4 leading-tight">Your Digital Healthcare Partner</h2><p class="text-gray-200 text-[0.85rem] sm:text-[0.92rem] leading-relaxed mb-5 font-light">QuickMed is committed to providing accessible, affordable, and authentic healthcare solutions. From genuine medicines to expert consultations, we bridge the gap between you and better health.</p><ul class="space-y-2 mb-6 text-gray-300 text-[0.82rem] sm:text-[0.88rem]"><li class="flex items-center gap-2">✅ <span class="font-bold text-white">24/7 Support</span> for all queries</li><li class="flex items-center gap-2">✅ <span class="font-bold text-white">Licensed Pharmacy</span> certified</li><li class="flex items-center gap-2">✅ <span class="font-bold text-white">Nationwide</span> 64 districts</li></ul><a href="about.php" class="btn btn-lime btn-sm sm:btn-lg text-[0.78rem] sm:text-[0.85rem]">Learn More About Us →</a></div>
        <div class="relative" data-aos="fade-left"><div class="absolute inset-0 bg-lime-accent rounded-full blur-[60px] opacity-15 animate-pulse"></div><div class="bg-white/10 backdrop-blur-md border border-white/20 p-5 sm:p-6 rounded-xl shadow-xl text-center relative"><div class="text-5xl sm:text-6xl md:text-7xl mb-3 animate-bounce">🏥</div><h3 class="text-xl sm:text-2xl font-bold text-lime-accent">Since 2025</h3><p class="text-gray-300 text-xs sm:text-sm">Serving Bangladesh with pride</p><div class="mt-4 grid grid-cols-3 gap-2 text-center"><div class="bg-white/10 rounded-lg p-2"><div class="text-sm font-bold text-white">100%</div><div class="text-[10px] text-gray-400">Genuine</div></div><div class="bg-white/10 rounded-lg p-2"><div class="text-sm font-bold text-white">24h</div><div class="text-[10px] text-gray-400">Delivery</div></div><div class="bg-white/10 rounded-lg p-2"><div class="text-sm font-bold text-white">64</div><div class="text-[10px] text-gray-400">Districts</div></div></div></div></div>
    </div>
</section>
<section class="relative z-20 -mt-6 sm:-mt-10 px-3 sm:px-4">
    <div class="container mx-auto"><div class="bg-white/95 backdrop-blur-xl rounded-2xl sm:rounded-3xl shadow-[0_12px_30px_rgba(0,0,0,0.10)] border border-white/30 p-4 sm:p-6 md:p-8 relative overflow-hidden"><div class="absolute top-0 right-0 w-48 h-48 bg-lime-accent/10 rounded-full blur-3xl -z-10 translate-x-1/2 -translate-y-1/2"></div><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 md:gap-5">
        <div class="group relative p-3.5 sm:p-4 rounded-xl border border-transparent hover:border-lime-accent/30 hover:bg-green-50/50 transition-all duration-300" data-aos="fade-up"><div class="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"><span class="text-[9px] font-mono font-bold text-lime-700 bg-lime-100 px-1.5 py-0.5 rounded">VERIFIED</span></div><div class="w-10 h-10 sm:w-12 sm:h-12 bg-deep-green/10 rounded-xl flex items-center justify-center text-xl sm:text-2xl mb-2.5 group-hover:bg-deep-green group-hover:text-white transition-all duration-300 shadow-sm relative">👨‍⚕️<span class="absolute -top-1 -right-1 flex h-2 w-2"><span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-lime-500 opacity-75"></span><span class="relative inline-flex rounded-full h-2 w-2 bg-lime-500"></span></span></div><h3 class="text-[0.85rem] sm:text-[0.92rem] font-bold font-mono text-deep-green mb-1 group-hover:text-lime-600 transition-colors">Doctor Review</h3><p class="text-gray-500 text-[0.72rem] sm:text-xs leading-relaxed">Every prescription <span class="font-bold text-gray-700">double-checked</span> by registered doctors.</p></div>
        <div class="group relative p-3.5 sm:p-4 rounded-xl border border-transparent hover:border-blue-200 hover:bg-blue-50/50 transition-all duration-300" data-aos="fade-up" data-aos-delay="80"><div class="w-10 h-10 sm:w-12 sm:h-12 bg-blue-50 rounded-xl flex items-center justify-center text-xl sm:text-2xl mb-2.5 group-hover:bg-blue-600 group-hover:text-white transition-all duration-300 shadow-sm">❄️</div><h3 class="text-[0.85rem] sm:text-[0.92rem] font-bold font-mono text-deep-green mb-1 group-hover:text-blue-600 transition-colors">Cold-Chain</h3><p class="text-gray-500 text-[0.72rem] sm:text-xs leading-relaxed">Insulin & vaccines in <span class="font-bold text-gray-700">temp-controlled</span> boxes.</p></div>
        <div class="group relative p-3.5 sm:p-4 rounded-xl border border-transparent hover:border-purple-200 hover:bg-purple-50/50 transition-all duration-300" data-aos="fade-up" data-aos-delay="160"><div class="w-10 h-10 sm:w-12 sm:h-12 bg-purple-50 rounded-xl flex items-center justify-center text-xl sm:text-2xl mb-2.5 group-hover:bg-purple-600 group-hover:text-white transition-all duration-300 shadow-sm">🛡️</div><h3 class="text-[0.85rem] sm:text-[0.92rem] font-bold font-mono text-deep-green mb-1 group-hover:text-purple-600 transition-colors">100% Authentic</h3><p class="text-gray-500 text-[0.72rem] sm:text-xs leading-relaxed">Sourced from <span class="font-bold text-gray-700">GMP Certified</span> manufacturers.</p></div>
        <div class="group relative p-3.5 sm:p-4 rounded-xl border border-transparent hover:border-orange-200 hover:bg-orange-50/50 transition-all duration-300" data-aos="fade-up" data-aos-delay="240"><div class="w-10 h-10 sm:w-12 sm:h-12 bg-orange-50 rounded-xl flex items-center justify-center text-xl sm:text-2xl mb-2.5 group-hover:bg-orange-500 group-hover:text-white transition-all duration-300 shadow-sm">💊</div><h3 class="text-[0.85rem] sm:text-[0.92rem] font-bold font-mono text-deep-green mb-1 group-hover:text-orange-600 transition-colors">Expert Counseling</h3><p class="text-gray-500 text-[0.72rem] sm:text-xs leading-relaxed">Free advice from <span class="font-bold text-gray-700">A-Grade Pharmacists</span>.</p></div>
    </div><div class="absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-lime-accent to-transparent opacity-40"></div></div></div>
</section>
<?php include 'includes/homepage/health_blog.php'; ?>
<?php include 'includes/homepage/news.php'; ?>
<?php include 'includes/homepage/testimonials.php'; ?>
<section class="relative bg-[#022c22] py-8 sm:py-12 md:py-14 overflow-hidden border-t-[3px] border-lime-accent">
    <div class="absolute inset-0 z-0 opacity-15 pointer-events-none" style="background-image: linear-gradient(#065f46 1px, transparent 1px), linear-gradient(90deg, #065f46 1px, transparent 1px); background-size: 32px 32px;"></div>
    <div class="container mx-auto px-3 sm:px-4 relative z-10"><div class="flex flex-col lg:flex-row items-center justify-between gap-6 sm:gap-8"><div class="lg:w-1/2 text-left w-full" data-aos="fade-right"><div class="inline-flex items-center gap-1.5 bg-lime-accent/10 border border-lime-accent/30 rounded-full px-3 py-1 mb-4"><span class="w-1.5 h-1.5 rounded-full bg-lime-accent animate-ping"></span><span class="text-lime-accent font-mono text-[10px] sm:text-xs font-bold tracking-widest uppercase">System Online</span></div><h2 class="text-[1.4rem] sm:text-2xl md:text-3xl font-bold text-white mb-3 font-mono leading-tight">NEED <span class="text-lime-accent">EMERGENCY</span> HELP?</h2><p class="text-gray-400 text-[0.82rem] sm:text-sm mb-5 font-mono leading-relaxed border-l-2 border-lime-accent pl-3">Certified pharmacists standing by on secured channel.</p><div class="flex flex-wrap gap-2.5"><a href="tel:09678100100" class="bg-lime-accent text-deep-green px-4 sm:px-5 py-2.5 font-bold font-mono text-[0.78rem] sm:text-xs tracking-wider hover:bg-white transition-all rounded-lg inline-flex items-center gap-1.5">📞 CALL HOTLINE</a><a href="contact.php" class="px-4 sm:px-5 py-2.5 border-[1.5px] border-lime-accent text-lime-accent font-bold font-mono text-[0.78rem] sm:text-xs hover:bg-lime-accent/10 transition flex items-center gap-1.5 rounded-lg">✉️ SEND MESSAGE</a></div></div><div class="lg:w-1/2 w-full" data-aos="fade-left"><div class="bg-black/60 backdrop-blur-md border-[1.5px] border-[#065f46] p-4 sm:p-5 rounded-xl font-mono relative shadow-[0_0_15px_rgba(6,95,70,0.4)]"><div class="flex gap-1.5 mb-3 border-b border-[#065f46] pb-2"><div class="w-2.5 h-2.5 rounded-full bg-red-500"></div><div class="w-2.5 h-2.5 rounded-full bg-yellow-500"></div><div class="w-2.5 h-2.5 rounded-full bg-green-500"></div><div class="ml-auto text-[#065f46] text-[10px]">TERMINAL_V.2.0</div></div><div class="space-y-2 text-[11px] sm:text-xs"><div class="flex justify-between text-gray-400"><span>> CONNECTING...</span><span class="text-lime-accent">SUCCESS</span></div><div class="flex justify-between text-gray-400"><span>> PHARMACIST STATUS...</span><span class="text-lime-accent">ACTIVE</span></div><hr class="border-[#065f46] opacity-40 my-2"><div class="grid grid-cols-2 gap-3 mt-3"><div class="bg-deep-green/50 p-2.5 border border-lime-accent/20 rounded-lg"><span class="text-[9px] text-gray-400 block mb-1 uppercase tracking-wide">Pharmacists Online</span><span class="text-lg sm:text-xl text-lime-accent font-bold" id="pharmacist-count">08</span></div><div class="bg-deep-green/50 p-2.5 border border-lime-accent/20 rounded-lg"><span class="text-[9px] text-gray-400 block mb-1 uppercase tracking-wide">Avg Response</span><span class="text-lg sm:text-xl text-yellow-400 font-bold">~2 MIN</span></div></div><div class="mt-3 text-lime-accent animate-pulse text-[11px]">> WAITING FOR INPUT<span class="blink-cursor">_</span></div></div></div></div></div></div>
</section>
<script>setInterval(()=>{const el=document.getElementById('pharmacist-count');if(el){const r=Math.floor(Math.random()*(12-5+1)+5);el.innerText=r<10?'0'+r:r;}},5000);</script>
<script>
async function addToCart(medicineId, shopId, quantity){
    quantity=quantity||1;const siteUrl='<?= SITE_URL ?>';
    try{
        const fd=new FormData();fd.append('medicine_id',medicineId);fd.append('shop_id',shopId);fd.append('quantity',quantity);
        const res=await fetch(siteUrl+'/ajax/add_to_cart.php',{method:'POST',body:fd});
        const txt=await res.text();let result;try{result=JSON.parse(txt);}catch(e){throw new Error(txt);}
        if(result.success){Swal.fire({icon:'success',title:'Added!',text:'Item added to cart',toast:true,position:'top-end',showConfirmButton:false,timer:2000,background:'#065f46',color:'#fff'});document.querySelectorAll('.cart-count, .absolute.-top-2').forEach(b=>{b.innerText=result.cart_count;b.classList.remove('hidden');});}
        else if(result.message==='login_required'){Swal.fire({icon:'warning',title:'Login Required',text:'Please login to shop',showCancelButton:true,confirmButtonText:'Login',confirmButtonColor:'#065f46'}).then(r=>{if(r.isConfirmed)window.location.href=siteUrl+'/login.php';});}
        else{Swal.fire({icon:'error',title:'Oops...',text:result.message,confirmButtonColor:'#065f46'});}
    }catch(e){console.error(e);Swal.fire({icon:'error',title:'Error',text:'Something went wrong',confirmButtonColor:'#065f46'});}
}
</script>
<?php include 'includes/footer.php'; ?>
